#!/usr/bin/env python

"""helloworld.py: Echo Hello World."""

__author__ = "Gunnar Guddal"
__copyright__ = "Copyright 2019"
__credits__ = ["Gunnar Guddal"]
__license__ = "GPL"
__version__ = "0.1"

print("Hello world")
